name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run tests
        run: yarn test --coverage

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run audit
        run: yarn audit

  artifacts:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    steps:
      - name: Upload production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Static Build folder
          path: |
            ./build
